remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

include:
  - _includes
  - assets/css/custom.css

markdown: kramdown
highlighter: rouge

# Custom CSS
style: /assets/css/custom.css